# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: front-eccomerce
#     ports:
#       - "3000:3000"
#     depends_on:
#       - redis
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379

#   redis:
#     image: redis:7.2-alpine
#     container_name: redis-server
#     ports:
#       - "6379:6379"
